name: Phase 4 — E2E export smoke
on:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run E2E
        run: |
          . .venv/bin/activate
          bash scripts/verify_phase4_e2e.sh
